#ifndef APP_PARAM_HPP
#define APP_PARAM_HPP

#ifndef APP_PARAM_ID_BASE
#define APP_PARAM_ID_BASE 0x10000000
#endif

#ifndef IDLE_TASK_PARAM_ID_BASE
#define IDLE_TASK_PARAM_ID_BASE APP_PARAM_ID_BASE + 0x100
#endif

#ifndef IDLE_TASK_PWR_ON_RESET_CNT_PARAM
#define IDLE_TASK_PWR_ON_RESET_CNT_PARAM IDLE_TASK_PARAM_ID_BASE + 0x0
#endif
 
#endif //APP_PARAM_HPP
