#ifndef GPIO_DEF_ATB_HPP
#define GPIO_DEF_ATB_HPP

#include <Fw/Types/BasicTypes.hpp>

extern const NATIVE_UINT_TYPE FPGA_GPIO_LENGTH;
extern const NATIVE_UINT_TYPE FPGA_GPIO_TOTAL_AVAIL_PINS;
extern NATIVE_UINT_TYPE FPGA_GPIO_PINS_ENABLE[];
extern const NATIVE_UINT_TYPE GPIO_PIN_LENGTH;
extern NATIVE_UINT_TYPE GPIO_PIN_NUMS[];
extern NATIVE_UINT_TYPE GPIO_PIN_DIR[];
extern NATIVE_UINT_TYPE GPIO_PIN_INT[];
extern NATIVE_UINT_TYPE GPIO_PIN_POL[];
extern NATIVE_UINT_TYPE GPIO_PIN_EDGE[];

#endif
