#include "GPIODefATB.hpp"
#include <fprime-sphinx-drivers/GPIODriver/GPIODriverComponentImpl.hpp>
#include <Fw/Types/Assert.hpp>
#include <App/Include/config.hpp>

const NATIVE_UINT_TYPE GPIO_PIN_LENGTH = 2;
NATIVE_UINT_TYPE GPIO_PIN_NUMS[] = {
  PIN_NUM_3, PIN_NUM_5,
};
FW_STATIC_ASSERT(GPIO_PIN_LENGTH == FW_NUM_ARRAY_ELEMENTS(GPIO_PIN_NUMS));

NATIVE_UINT_TYPE GPIO_PIN_DIR[] = {
  GPIO_OUT, GPIO_OUT,
};
FW_STATIC_ASSERT(GPIO_PIN_LENGTH == FW_NUM_ARRAY_ELEMENTS(GPIO_PIN_DIR));

NATIVE_UINT_TYPE GPIO_PIN_INT[] = {
  0, 0,
};
FW_STATIC_ASSERT(GPIO_PIN_LENGTH == FW_NUM_ARRAY_ELEMENTS(GPIO_PIN_INT));

NATIVE_UINT_TYPE GPIO_PIN_POL[] = {
  0, 0,
};
FW_STATIC_ASSERT(GPIO_PIN_LENGTH == FW_NUM_ARRAY_ELEMENTS(GPIO_PIN_POL));

NATIVE_UINT_TYPE GPIO_PIN_EDGE[] = {
  0, 0,
};
FW_STATIC_ASSERT(GPIO_PIN_LENGTH == FW_NUM_ARRAY_ELEMENTS(GPIO_PIN_EDGE));
